// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxfdexukpmnruleqxowa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4ZmRleHVrcG1ucnVsZXF4b3dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyNzUzNjAsImV4cCI6MjA4NTg1MTM2MH0.LM-kaUAWJx2KCupaL5TKVnwKTrYK1cgW5bx00D78K8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);